trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solutionName: 'MvvmFrame'
  solution: '**/$(solutionName).sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorVersion: '6'
  packageVersion: '$(majorVersion).$(Build.BuildNumber)'
  packageFileName: 'MvvmFrame.root.$(packageVersion).nupkg'
  nugetProjectName: 'MvvmFrame'

steps:
- template: pipeline_steps/step_install_snk.yml

- template: pipeline_steps/step_restore_build_pack.yml

- template: pipeline_steps/step_run_all_tests.yml

- template: pipeline_steps/step_copy_nuget_to_artifacts.yml

- task: NuGetCommand@2
  displayName: "NuGet push GetcuReone source"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/$(solutionName)/$(packageFileName)'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'd5079c70-9bc4-4da1-b3c9-feb9869dfc91'
